# Generated by Django 5.0.2 on 2024-04-08 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='o_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
    ]
