# Generated by Django 5.0.2 on 2024-04-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_payment_o_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='o_id',
        ),
    ]
