# Generated by Django 5.0.2 on 2024-03-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ucontact',
            fields=[
                ('uindex', models.AutoField(primary_key=True, serialize=False)),
                ('uemail', models.EmailField(max_length=50)),
                ('umessage', models.TextField()),
            ],
        ),
    ]
