# Generated by Django 5.0.2 on 2024-03-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_catagory_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pcolor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='psize',
        ),
    ]
