# Generated by Django 5.0.2 on 2024-04-08 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
    ]
